home page with login and fetch data
noadudai/KeepOnTimeShifts pull request #3
Opened 2024-12-25 11:21 UTC by noadudai

2024-12-25 12:10 UTC, timo-legit approved these changes

2024-12-25 12:10 UTC, timo-legit commented on front/src/components/login.tsx
> +const LoginButton = () => {
Do all like this. Not function() blabla

2024-12-25 12:10 UTC, timo-legit commented on front/src/main.tsx
> +         audience: secrets.secrets["REACT_APP_AUTH0_AUDIENCE"],}}>
Its a secret?? U cant have secrets in Frontend

2025-02-09 11:20 UTC, timopomer commented on front/src/main.tsx
> +const MyRouts = () =>{
my is a weird prefix.

also its `Routes`

2025-02-09 11:23 UTC, timopomer commented on front/src/main.tsx
> +        <Auth0Provider domain={"dev-huo4anz1ojy6ggvy.us.auth0.com"} clientId={"XcdHJiAoJoq9CHvgxGPtykyuywWhaa4Y"} authorizationParams={{ redirect_uri: "http://localhost:5173/info/",
de-hardcode this

2025-02-09 11:23 UTC, timopomer commented on front/src/main.tsx
> +        <Auth0Provider domain={"dev-huo4anz1ojy6ggvy.us.auth0.com"} clientId={"XcdHJiAoJoq9CHvgxGPtykyuywWhaa4Y"} authorizationParams={{ redirect_uri: "http://localhost:5173/info/",
use environment variables

2025-02-09 11:23 UTC, timopomer commented on front/src/pages/HomePage.tsx
> +        <div >
this div does nothing

2025-02-09 11:24 UTC, timopomer commented on front/src/components/InfoPageNavBar.tsx
> +import {RedirectLoginOptions} from "@auth0/auth0-react";
next PR add eslint to the ci/cd. to make sure the formatting is good

2025-02-11 13:01 UTC, timo-legit requested changes

2025-02-11 13:01 UTC, timo-legit commented on package.json
> +    "@noadudai/scheduler-backend-test": "^13262072765.38.1",
Only test?

2025-02-12 11:44 UTC, timo-legit approved these changes

2025-02-12 11:50 UTC, merged